import type { NextPage } from 'next'
import Head from 'next/head'
import ParallaxPageElement from '../components/main/parallaxPageElement'
//import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
      //<div className={styles.container}>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          <ParallaxPageElement />
      </main>

    </div>
  )
}

/*
*       <footer className={styles.footer}>

      </footer>
* */

export default Home
